[package]
name = "polygen"
version = "0.1.0"
edition = "2021"

[features]
no-ffi = ["polygen-proc/no-ffi"]
allow-unsupported = ["polygen-proc/allow-unsupported"]

[dependencies]
polygen-proc = { path = "./crates/polygen-proc" }
polygen-private = { path = "./crates/polygen-private" }
