[package]
name = "polygen"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
polygen-proc = { path = "./polygen-proc" }
serde = { version = "1.0", features = ["derive"] }
indexmap = { version = "2.0", features = ["serde"] }
