[package]
name = "all-features"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
polygen = { path = "../../" }

[dev-dependencies]
polygen-csharp = { path = "../../generators/polygen-csharp" }
